config:
    required: true

database:
    +:
        name: default
        namespace: Creonit\MediaBundle\Model
        defaultIdMethod: native

    gallery:
        +behavior:
            - timestampable

    gallery_item:
        gallery_id: int > gallery.id
        title: text
        description: text
        cover: bool = 0 key
        visible: bool = 1 key
        +behavior:
            - file
            - image
            - video
            - sortable
            - timestampable

    file:
        path: text
        name: text
        original_name: text
        extension: varchar(10)
        mime: varchar(100)
        size: int
        +behavior:
            - timestampable

    image:
        source: text
        +behavior:
            - file
            - timestampable

    video:
        source: text
        +behavior:
            - file
            - timestampable